// Expanded random data collections for template generators

export const RANDOM_DATA = {
	names: [
		'John Smith',
		'Jane Doe',
		'Mike Johnson',
		'Sarah Wilson',
		'David Brown',
		'Lisa Davis',
		'Robert Taylor',
		'Emily Anderson',
		'Michael Garcia',
		'Jessica Martinez',
		'William Rodriguez',
		'Ashley Hernandez',
		'James Lopez',
		'Amanda Gonzalez',
		'Christopher Wilson',
		'Michelle Moore',
		'Matthew Taylor',
		'Stephanie Thomas',
		'Anthony Jackson',
		'Jennifer White',
		'Mark Harris',
		'Laura Martin',
		'Steven Thompson',
		'Nicole Garcia',
		'Paul Martinez',
		'Karen Robinson',
		'Daniel Clark',
		'Betty Rodriguez',
		'Kenneth Lewis',
		'Helen Lee',
		'Jason Walker',
		'Donna Hall',
		'Ryan Allen',
		'Carol Young',
		'Benjamin Hernandez',
		'Sharon King',
	],

	emails: [
		'admin@example.com',
		'dev@company.com',
		'user@domain.org',
		'test@site.net',
		'support@business.com',
		'info@organization.org',
		'contact@enterprise.net',
		'webmaster@portal.com',
		'system@platform.org',
		'root@server.net',
		'administrator@system.com',
		'manager@office.org',
		'operator@control.net',
		'service@helpdesk.com',
		'tech@support.org',
		'backup@storage.net',
		'security@firewall.com',
		'monitoring@alerts.org',
		'logs@analytics.net',
		'database@cluster.com',
		'api@gateway.org',
		'cache@redis.net',
		'queue@worker.com',
		'mail@smtp.org',
		'ftp@files.net',
	],

	companies: [
		'TechCorp',
		'DataSoft',
		'WebSolutions',
		'InfoSystems',
		'CloudTech',
		'DigitalWorks',
		'SoftwarePlus',
		'NetSolutions',
		'CyberSoft',
		'CodeFactory',
		'InnovateLab',
		'TechPioneer',
		'DataStream',
		'CloudBridge',
		'SystemCore',
		'WebCraft',
		'DevStudio',
		'TechVision',
		'DigitalHub',
		'SmartSoft',
		'ProTech',
		'MegaSoft',
		'UltraCode',
		'PowerSoft',
		'NextGen',
		'FutureTech',
		'GlobalSoft',
		'PrimeTech',
		'EliteSoft',
		'AdvancedSys',
		'SecureTech',
		'FastTrack',
		'OpenSource',
		'FlexiSoft',
		'RapidDev',
	],

	projects: [
		'website',
		'api',
		'backend',
		'frontend',
		'mobile-app',
		'dashboard',
		'admin-panel',
		'user-portal',
		'e-commerce',
		'blog-system',
		'cms',
		'crm-system',
		'inventory',
		'analytics',
		'reporting',
		'monitoring',
		'payment-gateway',
		'auth-service',
		'notification-system',
		'file-manager',
		'chat-app',
		'forum',
		'wiki',
		'documentation',
		'landing-page',
		'microservice',
		'api-gateway',
		'data-pipeline',
		'scheduler',
		'worker-queue',
		'search-engine',
		'recommendation',
		'machine-learning',
		'ai-assistant',
		'automation',
	],

	domains: [
		'example.com',
		'company.org',
		'business.net',
		'site.com',
		'portal.org',
		'platform.net',
		'service.com',
		'system.org',
		'enterprise.net',
		'corporate.com',
		'tech-solutions.org',
		'data-systems.net',
		'web-services.com',
		'cloud-platform.org',
		'digital-hub.net',
		'smart-tech.com',
		'pro-systems.org',
		'secure-net.com',
		'fast-track.org',
		'global-tech.net',
		'innovation-lab.com',
		'future-soft.org',
		'mega-corp.net',
		'ultra-systems.com',
		'prime-tech.org',
		'elite-solutions.net',
	],

	apps: [
		'MyApp',
		'WebPortal',
		'Dashboard',
		'AdminPanel',
		'UserSystem',
		'DataManager',
		'FileExplorer',
		'TaskTracker',
		'ProjectHub',
		'TeamSpace',
		'CloudDrive',
		'SecureVault',
		'QuickNote',
		'SmartBoard',
		'FlexiCRM',
		'PowerBI',
		'DataViz',
		'ReportGen',
		'MonitorPro',
		'AlertSystem',
		'ChatBot',
		'MailMaster',
		'SyncTool',
		'BackupPro',
		'CleanMaster',
		'SpeedTest',
		'NetworkScan',
		'LogViewer',
		'DebugTool',
		'DevConsole',
	],

	databases: [
		'main_db',
		'user_data',
		'content_db',
		'analytics',
		'logs',
		'inventory',
		'orders',
		'customers',
		'products',
		'sessions',
		'cache_db',
		'backup_db',
		'archive',
		'reports',
		'metrics',
		'audit_log',
		'transactions',
		'payments',
		'notifications',
		'messages',
		'files_meta',
		'search_index',
		'user_prefs',
		'system_config',
		'temp_data',
		'queue_jobs',
		'error_logs',
		'access_logs',
		'performance',
		'monitoring',
	],

	users: [
		'admin',
		'user',
		'guest',
		'operator',
		'manager',
		'supervisor',
		'developer',
		'tester',
		'analyst',
		'support',
		'moderator',
		'editor',
		'viewer',
		'contributor',
		'reviewer',
		'approver',
		'publisher',
		'maintainer',
		'root',
		'system',
		'service',
		'daemon',
		'worker',
		'scheduler',
		'backup',
		'monitor',
		'logger',
		'security',
		'audit',
		'compliance',
	],

	passwords: [
		'password123',
		'admin2023',
		'secure123',
		'test1234',
		'qwerty789',
		'welcome2024',
		'changeme',
		'default123',
		'system2023',
		'secret789',
		'login123',
		'user2024',
		'pass123',
		'temp1234',
		'demo789',
		'123456789',
		'password1',
		'admin123',
		'root123',
		'guest123',
		'letmein',
		'welcome',
		'password',
		'12345678',
		'qwerty123',
	],

	comments: [
		'Production config',
		'Updated settings',
		'Backup configuration',
		'Legacy settings',
		'Development environment',
		'Testing parameters',
		'Staging configuration',
		'Local setup',
		'Docker settings',
		'Kubernetes config',
		'CI/CD pipeline',
		'Build configuration',
		'Security settings',
		'Performance tuning',
		'Cache configuration',
		'Database settings',
		'API endpoints',
		'Service discovery',
		'Load balancer config',
		'Monitoring setup',
		'Logging configuration',
		'Error handling',
		'Backup strategy',
		'Recovery settings',
	],

	serverNames: [
		'nginx/1.18.0',
		'Apache/2.4.41',
		'Microsoft-IIS/10.0',
		'nginx/1.16.1',
		'Apache/2.4.46',
		'nginx/1.20.2',
		'Apache/2.4.52',
		'Microsoft-IIS/8.5',
		'LiteSpeed/5.4.12',
		'Caddy/2.4.6',
		'Traefik/2.5.4',
		'HAProxy/2.4.8',
		'OpenResty/1.19.9.1',
		'Tengine/2.3.3',
		'IIS/10.0',
		'Apache/2.4.48',
	],

	poweredBy: [
		'PHP/7.4.3',
		'PHP/8.1.2',
		'ASP.NET',
		'Express',
		'Django/3.2.1',
		'PHP/8.0.12',
		'PHP/7.3.33',
		'Node.js/16.14.0',
		'Ruby/3.0.3',
		'Python/3.9.7',
		'Java/11.0.13',
		'Go/1.17.6',
		'Rust/1.58.1',
		'Laravel/8.75.0',
		'Symfony/5.4.2',
		'CodeIgniter/4.1.7',
		'CakePHP/4.3.5',
	],

	technologies: [
		'React',
		'Vue.js',
		'Angular',
		'Svelte',
		'Next.js',
		'Nuxt.js',
		'WordPress',
		'Drupal',
		'Joomla',
		'Magento',
		'Shopify',
		'WooCommerce',
		'MySQL',
		'PostgreSQL',
		'MongoDB',
		'Redis',
		'Elasticsearch',
		'MariaDB',
		'Docker',
		'Kubernetes',
		'Jenkins',
		'GitLab',
		'GitHub Actions',
		'Travis CI',
	],

	fileTypes: [
		'config',
		'settings',
		'parameters',
		'properties',
		'environment',
		'secrets',
		'backup',
		'dump',
		'export',
		'archive',
		'snapshot',
		'cache',
		'log',
		'debug',
		'trace',
		'audit',
		'access',
		'error',
		'temp',
		'tmp',
		'old',
		'bak',
		'orig',
		'save',
	],

	gitBranches: [
		'main',
		'master',
		'develop',
		'dev',
		'staging',
		'production',
		'feature/user-auth',
		'feature/payment',
		'feature/dashboard',
		'hotfix/security',
		'bugfix/login-issue',
		'release/v2.1.0',
		'experimental/ai-integration',
	],
};

export function getCompanyName(envCompanyName?: string): string {
	return envCompanyName || RANDOM_DATA.companies[Math.floor(Math.random() * RANDOM_DATA.companies.length)];
}

export function getCompanyDomain(envCompanyDomain?: string): string {
	return envCompanyDomain || getRandomItem(RANDOM_DATA.domains);
}

export function getAdminEmail(envAdminEmail?: string): string {
	return envAdminEmail || getRandomItem(RANDOM_DATA.emails);
}

export function getRandomItem<T>(array: T[]): T {
	return array[Math.floor(Math.random() * array.length)];
}
